# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:

  - name: Home
    identifier: b9324785
    url: /#top
    weight: 10
  - name: About
    identifier: 73d7cb83
    url: /#about
    weight: 20
  - name: Features
    identifier: 1c4c664f
    url: /#features
    weight: 30
  - name: News
    identifier: 2f7a15f4
    url: /news/
    weight: 40
  - name: Solutions
    identifier: e6684709
    url: /solutions
    weight: 50
  - name: Resources
    identifier: 755a61ed
    url: ""
    weight: 60
    hasChildren: true
  - parent: Resources
    name: blog/
    url: blog/
